title: My CS 1030 Website
author: Author Name
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
google_analytics:
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
